### ISSUE TITLE
Angular installation fails

### ISSUE THREAD

**Issue by vademo** [digipolisantwerp/starter-kit-ui_app_nodejs#55]
**CMD:**
```bash
digipolis-start-ui --no-setup --backend=nodejs --database=none --name=your-awesome-project-name --debug=true --frontend=angular --branding=Antwerp --no-auth=true
```
**Log:**
```log
============================================================================
============== Welcome to the Digipolis starter kit! (v2.1.3) ==============
============================================================================
Preparing...
Installing Angular...
internal/modules/cjs/loader.js:1083
  throw err;
  ^
Error: Cannot find module '/root/.npm/_npx/51/lib/node_modules/@angular/cli/bin/postinstall/script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

@TriangleJuice Ik leg dit even bij jou maar moest je meer uitleg hebben als wat hierboven staat laat het gerust weten dan kijk ik mee

**Comment by vademo** [comment]
Issues only in gitlab ci / docker: node 14.
Generating on Node 15+ seems to resolve this issue even though node 14 should still have support as it is LTS at this time. 

Solved but not fixed
